### PR TITLE
Add linting; use npm test to lint files

### PR DESCRIPTION
**Pull request by naomiajacobs**
Closes #38

### CODE REVIEW

**Comment by ryanwholey** [comment]
@naomiajacobs LINTING!! :+1: 

How do you feel about keeping the testData.json file around until we write up some real data? Maybe we should open an issue to create a real data file?

**Comment by ryanwholey** [comment]
ooh ooh! naoms can you remove "import { characters, players, user } from '../testData.jsx';" from line 1 in dataReducer.js also? it can't find file and sad red console explodes

**Comment by danthareja** [comment]
linting! :clap:

**Comment by naomiajacobs** [comment]
Yay linting! For the data, I think @xbrightmatterx was planning to get the db up and running soon; until then I'll write up a better test data file that better maps to our schema plan.

Re: the dataReducer.js, I thought it was already gone? It's gone in mine.

**Pull request merged**
